fix: improve dbc install error on driver not found (#339)
This improves the error message when a user tries to install a driver
that doesn't exist in any registry. The current behavior is,

```sh
$ dbc install sqlserver
Error: could not find driver: driver `sqlserver` not found in driver registry index
```

With this PR, the new behavior is,

```
$ go run ./cmd/dbc install sqlserver
Error: could not find driver: driver `sqlserver` not found in driver registry index; try: `dbc search` to list available drivers
```