fix: improve install and add error messages for pre-release drivers (#338)
Updates `dbc install` and `dbc add` to provide command suggestions for
pre-release drivers.

For example: Currently, if I try to dbc install a driver that only has a
pre-release available, I get an error message that isn't that helpful,

```sh
$ dbc install fakedriver
Error: driver `fakedriver` not found (but prerelease versions filtered out)
```

This PR updates the error so it recommends the user try `--pre`:

```sh
$ dbc install fakedriver
Error: driver `fakedriver` not found (but prerelease versions filtered out); try: dbc install --pre fakedriver
```

This error only happens if the driver _only_ has pre-release versions
and the user doesn't specify `--pre`. It's not a perfect heuristic but I
think it'll work well.